version: "3.9"
services:
  app:
    build: ./app
    environment:
      env_file: .env
    ports:
      - "3000:3000"
    container_name: app
    volumes:
      - ./app/src:/app/src

  streaming-api:
    build: ./streaming-api
    environment:
      env_file: .env
    container_name: streaming-api
    volumes:
      - ./streaming-api:/app/

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db:rw
      - mongoconfig:/data/configdb:rw
    networks:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8889:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    networks:
      - mongodb

volumes:
  mongodb:
    name: mongodb
    driver: local
    external: false
  mongoconfig:
    name: mongoconfig
    driver: local
    external: false

networks:
  mongodb:
    name: mongodb
    driver: bridge
