version: "3.9"
services:
  app:
    build: ./app
    environment:
      env_file: .env
    ports:
      - "3000:3000"
    container_name: app
    volumes:
      - ./app/src:/app/src
  streaming-api:
    build: ./api
    environment:
      env_file: .env
    container_name: streaming-api
    volumes:
      - ./api/
